### ISSUE TITLE
Leaflet crashes (possibly when changing between desktop and mobile viewports?)

### ISSUE THREAD

**Issue by marxian** [neontribe/gbptm#206]
Just a hunch, but I suspect that we don't adequately tidy up maps on unmount, and we get leftover event handlers firing after the map has been removed?

```
leaflet-src.js:2765 Uncaught TypeError: Cannot read property '_leaflet_pos' of undefined
    at getPosition (leaflet-src.js:2765)
    at NewClass._getMapPanePos (leaflet-src.js:4378)
    at NewClass.containerPointToLayerPoint (leaflet-src.js:3958)
    at NewClass._getCenterLayerPoint (leaflet-src.js:4415)
    at NewClass.getCenter (leaflet-src.js:3746)
    at LooMap.onMove (LooMap.js:145)
    at invokeFunc (lodash.js:10333)
    at trailingEdge (lodash.js:10382)
    at timerExpired (lodash.js:10370)
```

**Comment by Hoolean** [comment]
## Causes

This issue is typical of accessing a leaflet Map after it has been destroyed. For us, it is being caused in two places:
* [We debounce our onMove event handler](https://github.com/neontribe/gbptm/blob/ebf19718a6d3f37200101828fa1389257da5ce13/packages/ui/src/components/map/LooMap.js#L90-L93), meaning we call methods on the map potentially as late as 500ms after the map emits the event. During this time, the map may have been destroyed.
* Sometimes, the stack differs to our initial one within the Issue and it is fully contained within `leaflet`. This is unlikely to be our fault, as `react-leaflet` should clear up for us on unmount. It could be within this family of issues: Leaflet/Leaflet#155

## The State We're In

The issue appears to be silent; it does not cause any unexpected behaviour and the user is completely unaware of it.

It is safe for us to see how the situation improves as leaflet pushes further bug fixes; if we then find that the errors with stacks fully within `leaflet` disappear then we can address the debounce-related cause, which is our fault.
