### ISSUE TITLE
Clearly define multi-valued properties

### ISSUE THREAD

**Issue by Hoolean** [neontribe/gbptm#326]
Aside from changes to [redundant](https://github.com/neontribe/gbptm/issues/318) and [tri-state](https://github.com/neontribe/gbptm/issues/319) properties and [filler](https://github.com/neontribe/gbptm/projects/3) values, reports could still do with tighter restrictions on their values and clear definition of exactly what each value means.

With the migration to a new schema, we have an opportunity to make these changes to reports and also to remove any loos indicated to be irrelevant (e.g. customer-only loos).

Having seen a summary of the current report values, aside from the changes referenced above, some properties in particular seemed open to improvement; it would be great to hear thoughts on how we can tidy up here.

## [`access`](https://gist.github.com/Hoolean/3c8389fddaf7ede393bb2f87413b21d5#access)

There appears to be some ambiguity between values here; we'd probably benefit from limiting ourselves to a smaller number of values. In particular, I'm not sure of the purpose of the `"none"` category. Are there any preferences on which categories we trim down to and what we do with the loo reports in any categories we'd remove?

## [`type`](https://gist.github.com/Hoolean/3c8389fddaf7ede393bb2f87413b21d5#type) and [`accessibleType`](https://gist.github.com/Hoolean/3c8389fddaf7ede393bb2f87413b21d5#accessibletype)

The `"none"` categories are confusing here, as about 20 loo reports have this value for properties `type` **and** `accessibleType`; should we do validation to ensure that, at most, one of these at a time can be `"none"`?

## [`fee`](https://gist.github.com/Hoolean/3c8389fddaf7ede393bb2f87413b21d5#fee)

If we wanted to change the way the `fee` field works to add a clearer "yes"/"no" in addition to the user-provided text, now would be the time to consider how this would work in the schema and what attempts we'd make to migrate previous reports.

@gailramster I'd be interested to hear your thoughts on the state of these properties and on what would be useful for us to tidy and how.

**Comment by marxian** [comment]
@gailramster The core question for us here is whether the "None" value for access/type is useful to us?

We can only think that we have this in place to allow folk to express things like a disabled-only loo?

**Comment by Hoolean** [comment]
Some observations from the loos (not reports):

* **Of the 1455 loos with `access: "none"`, only 3 are active**
It is unlikely that `"none"` means anything meaningful here, so we can remove it as a value; what should be done with the loos that have it now?
* **Of the 34 loos with `type: "none"`, 17 are active** but, of these:
  * 9 indicate they have no `accessibleType` facilities either
  * 4 have unknown `accessibleType`
  * 4 have `accessibleType: "unisex"`
This seems like the only valid combination; what should be done with loos that have one of the others?
* **Of the 313 loos with `accessibleType: "none"`, 288 are active** but, of these:
  * 9 indicate they have no `type` facilities either
  * 35 have unknown `type`
  * 244, the rest, have a valid `type`
This seems like the only valid combination; what should be done with the loos that have one of the others?

**Comment by gailramster** [comment]
ACCESS = NONE
- No idea why 'none' exists - a leftover from the OSM import when there might be historical/closed public toilet blocks mapped that the public can no longer use? Users/we cannot select 'none' through the interface so I'd delete those 3.

TYPE = NONE
For the 9 with 'accessible type' = none, delete those reports
For 4 with 'accessible type' = unknown or 'accessible type' = unisex those would stay.

ACCESSIBLE TYPE = NONE
Again, remove the 9 with no type.
Keep 35 type = unknown and 244 type = none.

------------

The TYPE and ACCESSIBLE TYPE fields are trying to do 3 things, which is confusing. These are:

1) Is there access fo people who can use standard cubicles Yes/No; is there access for people who use accessible cubicles Yes/No. 

2) Are those cubicles gender-segregated or unisex?

3) Are they non-standard in some other way - children only, urinal only. 

This is why a report that is 'none' for one type and 'unknown' for the other is valid. It's saying that the 'unknown' facility definitely exists, but the user does not know if it is unisex or male & female. 

This is often the case when entering information from websites, as councils will say 'male, female, accessible' to show all 3 groups can access a toilet, but that doesn't mean they are using 3 different facilities (e.g. it may be a Costa where there's one accessible toilet that all users share). 

There would be many, many more toilets in these 'unknown' categories if I added information faithfully, but I often make assumptions e.g. that the accessible toilet is unisex, as it seems better for users to be clear there IS a toilet there they can use, even if I've got the gender/unisex option wrong. 

-------
Future half-baked Ideas (will add properly to Github when baked unless this fits somehow with your rejig, but sharing for info now)
My preference, which may be longer term/not possible, would be to have a clearer question. 

e.g. 1) who can access these toilets? - tick all that apply: men / women / accessible toilet users / children only / urinal only. (although the last two are not 'all that apply' really) 

This would be based on 'what signs are on the doors' and maybe could use icons of the male/female/wheelchair symbols to illustrate the point (an accessible toilet in a costa would show all 3 symbols if it was for everyone). 

Baby-changing could also be visually grouped to this section, and we lose 'Attended' as a category. 

It would then be easier to add other 'types' in the future, e.g. Family toilet, Feeding room, Changing Places toilet, and to activate searches based on these. 

It would be nice to say whether a toilet had separate male/female facilities, or shared, or if everyone was using an accessible toilet, but perhaps this falls under 'nice to have' rather than essential, and could be communicated one day by a photo. 

Conclusion: Requires Thought. 

Automatic is useful but may be a dying breed. 
Radar Key is still useful. It may be more complex, to know whether an accessible toilet is only accessible by Radar, or accessible to all but has longer hours with a Radar, but we'd need user feedback.  These could be visually grouped with Payment questions. 





-----------

**Comment by Hoolean** [comment]
I've had another look at the data side of this issue:

* The reports with `"access": "none"` look very normal aside from that quirk so I'll probably just strip out that property instead of removing them entirely
* 8/9 of the reports with `"type": "none"` and `"accessibleType": "none"` look like deletion reports that neglect to set active and so I will convert the 8 proper ones into removal reports, deleting the other

This should be an improvement over just removing them.

**Comment by Hoolean** [comment]
The patching described in the comment above is implemented with 4a508f41533c4c5926adc6211f37dfabccee00e8. 

We can either bind `"access"`, `"type"` and `"accessibleType"` to a specific set of values, to ensure the data doesn't become messy again post-migration, or we can make a more radical change to the schema, as now is a convenient time to do so.
