### ISSUE TITLE
New options for Opening Hours

### ISSUE THREAD

**Issue by marxian** [neontribe/gbptm#332]
**Is your feature request related to a problem? Please describe.**
Lots of businesses can't fir in our current selection of opening hours

**Describe the solution you'd like**
Add "noon to 11pm" to the options

**Describe alternatives you've considered**
We'd love a really configurable picker for this, but probably don't currently have time.

**Comment by marxian** [comment]
The opening hours configurations are held in a subpackage here: https://github.com/neontribe/gbptm/tree/develop/packages/opening-hours

**Comment by gailramster** [comment]
I'm not sure more options is that helpful, from the perspective of getting the 'is it open now?' feature to work. 

We could add more opening-closing options like noon-11pm (reflecting pub-style hours ) but they're still unlikely to be correct for more than a handful of pubs, or everyday of the week. 
Ideally I'd like one reflecting the new Welsh standard https://gov.wales/docs/dhss/publications/technical-guidance-local-toilets-strategies.pdf (also in screenshot, apart from rest of the list of bank holidays) - e.g. click radio. button for Is it open on: Mon / Tues / Weds / Thurs / Fri / Sat / Sun then if Yes is returned, show fields to enter opening and closing times, then a note for seasonal. (still not perfect but covers the 80% instead of the 20% of instances). 

Or, we go more vague - 'open mornings and/or afternoons and/or evenings? weekdays and/or weekends? Or other? I'm less concerned about losing the current information captured through user-contributions in the existing opening hours field as I doubt there's many that are meaningful or accurate. The opening hours present not through the interface but from the original GBPTM dataset  may be more accurate, but 6 years old. 

One quick improvement might be telling people what 'business hours Mon-Fri' and 'Mon-Sun' means in terms of our coding (9am-5pm?). Fewer people will use it, but the data will be better. Or a note to say 'if 'other', enter details in Notes.

Depends how long term you're thinking.
