### ISSUE TITLE
Header is obstructive on smaller screens

### ISSUE THREAD

**Issue by marxian** [neontribe/gbptm#336]
**Describe the bug**
Since the addition of the domestos branding users have reported that they are almost unable to see the map.

**To Reproduce**
I'm not having much luck reproducing these examples in the devtools :-(

**Expected behavior**
The header should have a special representation on smaller devices

**Screenshots**
See attatched screenshots from social media

![image002](https://user-images.githubusercontent.com/474621/44398703-b6e6cd00-a53c-11e8-8d25-61d583055eae.png)
![image001](https://user-images.githubusercontent.com/474621/44398705-b8b09080-a53c-11e8-9d02-a5077ce3d769.png)

**Smartphone (please complete the following information):**
 Precise reported versions aren't available

**Comment by gailramster** [comment]
1) where are comments from? Public source of email? I like a good source of feedback, even bitching.
2) overlaps with #314 - hadn't realised it was this bad, with our logo covering several lines rather than shrinking as a graphic, too. The Domestos Blog is really the wrong shape for the space - lots of white above and below 'proudly sponsored by'

**Comment by marxian** [comment]
@gailramster I'd assumed you were in the original email thread :-(

I've forwarded it to you.

**Comment by marxian** [comment]
@falconx suggest this treatment on very small screens:

![gbptm-logos](https://user-images.githubusercontent.com/474621/44453092-279af180-a5f0-11e8-8170-9ae7b565f41b.png)

**Comment by marxian** [comment]
This is approved and will also fix 314
