### ISSUE TITLE
Populate db with area data (for use in toilet queries)

### ISSUE THREAD

**Issue by ob6160** [neontribe/gbptm#404]
Instead of querying `mapit` for area data upon the creation of each new report we want to simply load area data into the mongo database and use geo-queries in order to determine in which area a toilet exists.

## Plan
- [ ] removal of existing mapit query code in report generation
- [ ] sourcing area data *(specifically boundary polygons, likely in geojson format)* from a service such as ONS or [MapIt](https://mapit.mysociety.org/docs/#api-by_area_id)
- [ ] importing area boundary data into a mongodb collection with accompanying schema
- [ ] method of updating area boundaries reliably
- [ ] thought put into how queries will be structured to make use of area boundary info
- [ ] thought put into how existing area info tied to loo objects will be safely removed from the db (perhaps we run a query once on live or use the existing work on migrations)
- [ ] queries translated into a UI or API which allows end user to execute queries for toilets based on boundaries

## Acceptance Criteria
- [ ] Area boundaries are loaded into the mongo database
- [ ] Area boundaries can be freshened reliably from a known source
- [ ] Database can be queried to find toilets within area boundaries
- [ ] Admin UI allows for users to construct queries of their own (potential to shard into another ticket? @marxian)

## Useful links
* ### MapIt
  - https://mapit.mysociety.org/area/2514.html, https://mapit.mysociety.org/area/2514.geojson
  - https://mapit.mysociety.org/legal/#licensing
* ### ONS Digital Boundaries
  - https://www.ons.gov.uk/methodology/geography/geographicalproducts/digitalboundaries
  - https://www.ons.gov.uk/methodology/geography/ukgeographies/censusgeography

**Comment by marxian** [comment]
@jthistle This is an early version of the rework of areas we were talking about...

The plan needs refinement.

**Comment by jthistle** [comment]
- possible shapefile source: [ONS Local Authority Boundaries](https://geoportal.statistics.gov.uk/datasets/local-authority-districts-december-2019-boundaries-uk-bgc), provides shapefiles for download. Available at different resolutions (full res, 20m, 500m).

- how to change area system: instead of assigning loos an area by querying an external api on a report submit, query the loo area from mongo separately when querying loo details

- this requires importing ONS shapefiles into mongo, via an automated script if possible

- to think about:
  - what about an interactive explorer chloropleth map with areas on it?
  - How can we serve shapefiles at different resolutions for this map?
  - How does mongo perform with different resolutions when querying for the area that a point falls in?
  - What about areas of the UK that don't fall in a given ONS shapefile? Do we need a fallback system?

### Links

- [MongoDB GeoJSON docs](https://docs.mongodb.com/manual/reference/geojson/index.html)
- [All ONS local authority files](https://geoportal.statistics.gov.uk/search?collection=Dataset&sort=name&tags=all(BDY_LAD%2CDEC_2019))
- [React Simple Maps](https://www.react-simple-maps.io/examples/usa-counties-choropleth-quantize/)

**Comment by jthistle** [comment]
https://github.com/jthistle/areaToDatabase

**Comment by jthistle** [comment]
https://github.com/neontribe/gbptm/tree/404-areas-from-db
