### ISSUE TITLE
Blank radio fields default to 'no'. 

### ISSUE THREAD

**Issue by gailramster** [neontribe/gbptm#41]
Leaving the Attended/Baby-changing/Automatic/Radar fields on 'Don't know' when adding a new toilet defaults to No. 

Not possible to change a field from Yes/No back to Don't know.

**Comment by RoboPython** [comment]
The issue was that the checkboxes were being saved as Boolean, which automatically converts undefined to false. Now it uses strings with true,false and Not Known, fix pushed to testCreation branch, waiting for Rupert's approval

**Comment by RoboPython** [comment]
Fix works but just uncovered an issue with legacy Loos (obviously) that still contain the boolean value, so currently writing a conversion script.

**Comment by RoboPython** [comment]
Update: Did more investigation today, it turns out some fields were actually null somewhere along the line, I believe either mongoose or the templating engine didn't work well with having null values, so the fix still holds you just also need to do this on each:

db.loos.update({'properties.property':null},{'$set':{'properties.property':"Not Known"}},{multi:true})

**Comment by marxian** [comment]
Deployed to production
