### ISSUE TITLE
Look at different systems for CSS

### ISSUE THREAD

**Issue by charlesstrange2** [neontribe/gbptm#442]
It has been suggested that we could rewrite the CSS system.

we can use SASS inplace of .module.css ?

Comment below!

**Comment by jthistle** [comment]
Styled JSX is something I personally really like, and it's not too difficult to get it working. (It does require modifying the webpack/babel config for react though, which can just about be done without ejecting. I've done it a few times.)

Styled JSX is pretty cool because it can be changed dynamically based on the component's state. It also keeps all the css together with the components, and prevents name clashes. It's a really nice pairing with react.

The only downside I can think of is that setup is slightly tricky.

**Comment by marxian** [comment]
Let's shelve this until we can see the shape of the redesign
